### ISSUE TITLE
Security policy needed

### ISSUE THREAD

**Issue by mbartlett21** [http-server-rs/http-server#146]
It would be good to have a SECURITY.md document that isn't just a template.

**Comment by LeoBorai** [comment]
Hey @mbartlett21! Thanks for opening this issue!

Yeah, I totally agree with you, for the moment I started to write a security policy I was following on some read about the topic but I didn't got to a conclusion that satisfied my expectations.

I'm aiming to have weekly dependency updates and releases to always include the latest security patches and performance improvements.

Then if some vulnerability is detected in some package:

- Update the package in Cargo.toml
- Rebuild and Release
- Somehow notify users about an important update when running the server

We could provide some update check on first run for every 4 days or on a weekly basis.

What do you think? Im glad to hear about your suggestions and how would you approach this!

Thanks again!

**Comment by LeoBorai** [comment]
@mbartlett21 I have open a PR so I can have some suggestions from you.
