### ISSUE TITLE
Filesystem paths are not urlencoded

### ISSUE THREAD

**Issue by olivia-fl** [http-server-rs/http-server#163]
**Description**

File paths are templated into the html verbatim. Handlebars inserts html escape characters, but this doesn't handle things like filenames containing spaces correctly.

**Steps to reproduce**

1. `touch 'file with spaces.txt'`
2. Execute `http-server -h 127.0.0.1 -p 8080
3. Open http://127.0.0.1:8080
4. Click the `files with spaces.txt` link
5. The url is `http://127.0.0.1:8080/files`, which returns a 404

**Environment**

HTTP Server Version: v0.1.0
Operative System: Linux

**Comment by LeoBorai** [comment]
Hi @Benjamin-L!

Thanks so much for your interest on this crate and opening this issue. I was able to reproduce the bug locally, a PR will be landed soon addressing the issue.

**Comment by LeoBorai** [comment]
@Benjamin-L a PR is available on #164! If you have any feedback please share it there!
