### ISSUE TITLE
Better Proxy Support

### ISSUE THREAD

**Issue by za-songguo** [http-server-rs/http-server#219]
**Description**

Like this: 
```
Request from the front end: /api/something

To the backend API: localhost:8000/something
```
Requests should be forwarded to the backend (without the path prefix `/api`)

**Why is this useful?**

It is useful in the most of the web applications 😄

**Comment by LeoBorai** [comment]
Hi @za-songguo!

This is actually a great idea! Thanks for sharing! At the moment I'm a bit busy but in the next days I'm likely to have more time to tackle this!

If you want to work on this let me know so I can assign this issue to you! Count on me for any questions you may have!

**Comment by za-songguo** [comment]
> 
Thanks for your reply, I am reading the source code to understand how this library works

**Comment by za-songguo** [comment]
> Hi @za-songguo!
> 
> This is actually a great idea! Thanks for sharing! At the moment I'm a bit busy but in the next days I'm likely to have more time to tackle this!
> 
> If you want to work on this let me know so I can assign this issue to you! Count on me for any questions you may have!

Thanks for your reply, I am reading the source code to understand how this library works

**Comment by LeoBorai** [comment]
Hi @za-songguo! Any news on this?

**Comment by za-songguo** [comment]
@EstebanBorai Maybe we need some help, I have been working on embedded development lately and have no time for it.

**Comment by LeoBorai** [comment]
> @EstebanBorai Maybe we need some help, I have been working on embedded development lately and have no time for it.

Thanks for notifying!

**Comment by LeoBorai** [comment]
With new architecture I think a plugin can be implemented for this.
