### ISSUE TITLE
Migrate to Axum

### ISSUE THREAD

**Issue by LeoBorai** [http-server-rs/http-server#284]
Axum has increased popularity lately, it would be nice to begin migrating this
solution to Axum.

Axum already provides compatibility with Tower middleware which is great given
that tower has a mature community, so most of the features can be built out of the box!

**Comment by Phosphorus-M** [comment]
Yeah I agree with you, Axum has better support, the Tokio team is behind of this project maybe in sometime will be the standard in Rust to do webservers

**Comment by LeoBorai** [comment]
> Yeah I agree with you, Axum has better support, the Tokio team is behind of this project maybe in sometime will be the standard in Rust to do webservers

Awesome! Thanks for the feedback!

**Comment by Miuler** [comment]
Does this branch #feat/axum and PR #287 have to do with this issue?

**Comment by LeoBorai** [comment]
> Does this branch #feat/axum and PR #287 have to do with this issue?

Hi @Miuler! This is a follow up for a [milestone](https://github.com/http-server-rs/http-server/milestone/1),
when a version with Axum is released this issue (along with the milestone) will be closed.

**Comment by LeoBorai** [comment]
Follow on #313
