### ISSUE TITLE
Allow for SPA Routing Serving `index.html` for every request

### ISSUE THREAD

**Issue by LeoBorai** [http-server-rs/http-server#299]

**Comment by lucas-labs** [comment]
Hi! I see this was already implemented in #420. 
Any chance to get an update crates.io release? =D

Thanks!

**Comment by LeoBorai** [comment]
Hi @lucas-labs!

Thanks for pointing this out, HTTP Server has been released, here are the included changes:

https://github.com/http-server-rs/http-server/releases/tag/v0.8.9

Please feel free to open an issue or PR if you find any problem!
