### ISSUE TITLE
"http-server.exe --port 80 --username user --password password" how do i login?

### ISSUE THREAD

**Issue by FU3X** [http-server-rs/http-server#302]
{"status_code":401,"message":"Unauthorized"}

**Comment by EstebanBorai** [comment]
Hi @FU3X! Thanks for opening this issue!

When using the `--username` and `--password` options you're enabling the Basic Authentication check te check for those values.

You must send a HTTP request providing the `Authorization` HTTP header with a value that follows the `Basic` scheme.

```
Authorization: Basic username:password
```

The string `username:password` must be Base64 encoded.
You can read more here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#basic_authentication
Theres also a crate to help you with this here: https://lib.rs/crates/http-auth-basic

Have fun!
