### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Skateug30** [http-server-rs/http-server#358]
**Description**

Elaborate a bit on the feature you would like to have implemented on this project,
what does this feature brings to the project?

**Why is this useful?**

Why do we need this?

**How should this work?**

Steps on how to use this feature, what is the expected behavior?
Please provide as much detail as possible in order to have a fructiful
discussion on how to implement this.

**Comment by EstebanBorai** [comment]
I think this was a mistake! Closing!
