### ISSUE TITLE
[Issue Report] last<tr> overflows the table

### ISSUE THREAD

**Issue by Antosser** [http-server-rs/http-server#361]
Last row in the table is not completely visible

**Steps to reproduce**

1. Run the executable in a directory with a lot of files in it.
2. Open the link
3. Notice that the last item is not completely visible

**Environment**

HTTP Server Version: v0.8.6
Operative System: Windows

**Screenshots**

![image](https://github.com/http-server-rs/http-server/assets/71790328/b4e19235-bd33-41c0-89fe-cd7dc83fde25)
Notice that I completely scrolled down

https://github.com/http-server-rs/http-server/assets/71790328/bb120ba3-f1d8-4090-ad51-4ff43a283c19

Website Snapshot: https://mega.nz/file/J8cwSSyA#8ioa2D-nT8pyi_xn9lowMXP_WtPGR5NgrmHAJSwGam0

**Comment by Antosser** [comment]
I'd be happy to fix this issue myself. Just assign it to me

**Comment by LeoBorai** [comment]
Great! Thanks so much @Antosser!

**Comment by Antosser** [comment]
#369
