### ISSUE TITLE
[Feature Request] Make app verbose by default

### ISSUE THREAD

**Issue by Antosser** [http-server-rs/http-server#362]
When you just start the application, it prints nothing. You have no idea which port the app is on and which host it's hosted on. It is also much more practical to just click the link in the terminal than to manually write it in the browser.  

So, why not make it verbose by default? New users won't get confused and others will save a couple keystrokes on -v.  
  
Completely remove the `-v` flag and instead add a `-q` flag, which stands for `quiet`

**Comment by Antosser** [comment]
I'd be happy to fix this issue myself. Just assign it to me

**Comment by LeoBorai** [comment]
Thanks for the help @Antosser!

**Comment by LeoBorai** [comment]
Feel free to reach me if you need any help!
