### ISSUE TITLE
[Feature Request] Unnecessary getters on Config sturct

### ISSUE THREAD

**Issue by Antosser** [http-server-rs/http-server#401]
https://github.com/http-server-rs/http-server/blob/7eabb9b02b678f2f5b0df1f27948a99c1f484409/src/config/mod.rs#L4

I really don't understand why you'd want getters for these fields. It seems unnecessary because you could simply make the fields public.

If the goal was to make the fields immutable, you could just instantiate the struct without the `mut` keyword

**Comment by LeoBorai** [comment]
I agree with you!

Given that this was my first Rust project, back in the day I had other POV on software design!

Good observation!

PR welcome!

**Comment by Antosser** [comment]
I'd wait for #374 before doing this one because I don't really want to introduce any merge conflicts

**Comment by LeoBorai** [comment]
> I'd wait for #374 before doing this one because I don't really want to introduce any merge conflicts

Sgtm!

**Comment by Antosser** [comment]
I'll get on with this one since #374 is done
