### ISSUE TITLE
[Feature Request] Provide binaries for download

### ISSUE THREAD

**Issue by Emilgardis** [http-server-rs/http-server#92]
**Description**

Provide github releases with binaries to download

**Why is this useful?**

Provides the ability to use the project without installing rust on the machine and then compiling it.

**How should this work?**

Upload binaries for linux/amd64 and possible other targets. These can be made with CI with some available GH actions workflows

**Comment by LeoBorai** [comment]
Hi @Emilgardis!

Thanks for taking the time to open this feature request!

I totally agree with you, we could start by providing build artifacts for the three main OS supported by GitHub actions and then move into a more granular implementation by using Rust targets, what do you think?

**Comment by Emilgardis** [comment]
Awesome! Thank you 🎉
